### ISSUE TITLE
Join Filtering

### ISSUE THREAD

**Issue by lthiery** [helium/packet-purchaser#18]
Currently, we are using Packet Purchaser as a default Router and all offers are routed to it.

We need to enable Join purchasing in this configuration by creating an allow-list of EUI pairs per upstream LNS endpoint. Later, packet purchaser may want to do this via on-chain filters, but since we get all of the offers currently, we need to filter the offer off-chain.

**Comment by jdgemm** [comment]
This sounds good, thanks for raising it, added to backlog.

**Comment by lthiery** [comment]
https://github.com/helium/packet-purchaser/pull/19
